// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBebAi7veB2DgOiVcPiEgGRpgtkJidBUsc',
    appId: '1:500166558232:android:9549878d6a0a0aa861396d',
    messagingSenderId: '500166558232',
    projectId: 'calligro-bcfb2',
    storageBucket: 'calligro-bcfb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3ErEEVSf1ATwGEUoF--wYGJgbzKz43vU',
    appId: '1:500166558232:ios:47d23de02bf40a6d61396d',
    messagingSenderId: '500166558232',
    projectId: 'calligro-bcfb2',
    storageBucket: 'calligro-bcfb2.firebasestorage.app',
    androidClientId: '500166558232-vhlen07r2klgket5fbeeegtchlbsdl5h.apps.googleusercontent.com',
    iosClientId: '500166558232-aegg8epoq3ffo3b0klbgqvcl6jilq80j.apps.googleusercontent.com',
    iosBundleId: 'com.yazan.calligroApp',
  );
}
